CREATE DATABASE TASK_MANAGEMENT;
CREATE TABLE users(
	user_id uuid PRIMARY KEY NOT NULL default uuid_generate_v4(),
	name VARCHAR(30) NOT NULL,
	surname VARCHAR(30) NOT NULL,
	email VARCHAR(30) NOT NULL,
	password VARCHAR(60) NOT NULL,
	status VARCHAR(10) NOT NULL,
	date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	date_modified TIMESTAMP DEFAULT ON UPDATE CURRENT_TIMESTAMP
)